canonical/steam-snap

snap/snapcraft.yaml

Added two additional libraries to the alsa-mixin
- libsndfile
- libasyncns (which is marked as unsatisfied dependency for the alsa-mixin during snap build)
```
Priming alsa-mixin 
+ snapcraftctl prime
This part is missing libraries that cannot be satisfied with any available stage-packages known to snapcraft:
- libasyncns.so.0
- libogg.so.0
```
Tested and verified audio in the store was back after including those two.
libasyncns is not an audio related lib but since it's related to the alsa-mixin I've put them all together.

fix audio playback in the Steam webview, fixes #3

---

src/desktop-launch

At present when launching Linux native games using the snap, Nvidia graphics aren't detected and defaults to software rendering using llvmpipe. This change allows Vulkan to be used with Nvidia GPUs by adding the path to the `nvidia_icd.json` file to the `VK_ICD_FILENAME` environment variable, which previously wasn't set by the snap.

set VK_ICD_FILENAMES to allow NVidia Vulkan to work

---

snap/snapcraft.yaml

Some games attempt to load the Qt platform plugin for wayland, we probably don't want to use wayland for steam yet anyway.

Disable wayland support, fixes #22

---

snap/snapcraft.yaml

Attempts to fix #5 by including `locales-all` in `stage-packages`. Seems to allow me to type non ASCII characters like Russian into the client now.

Include locale data in snap to support non-ASCII input

---

snap/snapcraft.yaml

Adds [GameMode](https://github.com/FeralInteractive/gamemode) via [my fork](https://github.com/ashuntu/gamemode/tree/add-snap-support), including small changes to allow Snaps to be considered sandboxed. This should hit [xdg-desktop-portal](https://github.com/ashuntu/xdg-desktop-portal/tree/snap-support) if the user is running a build that handles Snaps.
To use GameMode, right-click on a game in your Library, click 'Properties...', and add the following to 'Launch Options':
```shell
gamemoderun %command%
```
If you have a compatible portal build running, your game should then be listed when running `gamemodelist` (outside of the Snap).

Add GameMode

---

snap/snapcraft.yaml

Added prime directive to the GameMode part to include `usr/bin/gamemoderun` and `usr/lib/*/libgamemode*.so.*`.
Issue #42

Prime gamemoderun and libgamemode.so files

---

snap/snapcraft.yaml

During startup, an error is displayed about a missing symbol when linking the Radeon and SWRast drivers:
libGL error: MESA-LOADER: failed to open radeonsi: /snap/steam/x8/usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so: undefined symbol: xcb_dri3_buffers_from_pixmap_strides (search paths /snap/steam/x8/usr/lib/i386-linux-gnu/dri:/snap/steam/x8/usr/lib/x86_64-linux-gnu/dri, suffix _dri) libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /snap/steam/x8/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so: undefined symbol: xcb_dri3_buffers_from_pixmap_strides (search paths /snap/steam/x8/usr/lib/i386-linux-gnu/dri:/snap/steam/x8/usr/lib/x86_64-linux-gnu/dri, suffix _dri) libGL error: failed to load driver: swrast
The problem is because steam includes, by …

DT-709: fix linking error

---

snap/snapcraft.yaml

The snap store has a limit of 30 elements in the Layout section. After the last patch, the number was bigger, so this MR fixes this. To do so, it:
- removes all the individual i386 bindings and does a single bind for /usr/lib/i386-linux-gnu (this implies to also copy all the i386 files from Core22)
- removes unused entries; specifically the mesa and mesa-egl bindings, since those folders don't exist anymore, neither in the x86_64 section, nor in the i386 section.
It also fixes the $SNAP/lib/steam bind, pointing it to $SNAP/usr/lib/steam.

Distribute the whole i386 libraries

---

src/steamreport

Added a new data point for the snapd revision, and renamed `revision` to `steam_revision` for clarity.

Add snapd revision to steamreport

---

src/steamreport

Adds --verbose and --force options to steam.report
steam.report will fail gracefully when encountering key errors for the likes of `lscpu`, `glxinfo`, etc.
Adds fallback os-release path
Adds lspci output for VGA devices
Output string is vertically aligned

steamreport: Add --verbose and --force options, fail gracefully on error

---

src/desktop-launch

This fixes Big Picture mode (and a few other fonts that were using system fallback fonts instead of vendored ones) by removing the fontcfg handling from the `desktop-launch` script entirely. At first I tried adding all font configurations *not* somewhere in `steamapps/common` (which includes things such as Steam VR and various versions of the Steam Linux Runtime), just because it's impossible to do that programmatically because most have versioned directories. However, this caused Steam to break even worse. The commit is in there so we can look at it in the future without having to redo the work I did and tweak it, and thus should probably not be squashed out.
fixes #5

Fix fonts in Big Picture (and elsewhere)

---

snap/snapcraft.yaml

This uses the new Snapcraft feature to silence lints on 32-bit libraries.
Previously you would always get a litany of warnings that it cannot determine
dependencies for any i386 libraries, this makes it not bother to check them.
This does not affect the final build in any way - it is purely a development
QOL change.

Silence bad 32-bit lints

---

snap/snapcraft.yaml

This finally lets my PS5 controller work in games! This should really just be merged ASAP IMO, it more or less completely fixes controller support (provided you have the udev rules installed outside the Snap).

Add usbutils for controller support

---

snap/snapcraft.yaml

This allows steam to monitor power on/off status, which seems to let it fix the UI when waking from sleep on laptops.
Fixes #28

Add upower support for sleep issues

---

snap/snapcraft.yaml

This reverts commit d48d370626c6fb7e54cd820ed059214446281cbf.
Temporarily revert `uinput` plug addition because we need permission for it to publish.

Revert "Add uinput plug for virtual controller"

---

snap/snapcraft.yaml
src/desktop-launch
tests/glx
tests/run.sh
tests/vulkan

* Fixes some layouts to point to relevant files in $SNAP/graphics/
* Fixed VK_ICD_FILENAMES to use icd files from the graphics content interface
* Added vkcube, vulkaninfo, glxinfo, and glxgears to apps to ease debugging
* Added a check for connection of the gaming-mesa content interface

Vulkan layout fixes

---

src/vulkaninfo

This fixes the Vulkaninfo test script - it will not properly fail when no physical device info is tested. Previously "" would always be passed and the -e flag wasn't used, preventing it from returning a non-zero exit value.

Fix vulkan test script

---

src/steam-snap.sh

steamapps is the default games directory. It must exist inside the snap, otherwise it gets created on launch
config/libraryfolders.vdf contains entries for the default games directory + secondary directories

fix steam-snap.sh that links deb game lib to snap game lib

---

src/steamreport

Adds `$XDG_CURRENT_DESKTOP` and `$DESKTOP_SESSION` as entries in `steam.report`.
*I guess I should have realized using `$` would substitute in the commit message...*

Add XDG_CURRENT_DESKTOP and DESKTOP_SESSION

---

src/steamreport

Example:
```
$ GITHUB_ACCESS_TOKEN="my_github_token" src/steamreport --summary
Gathering most recent 100 reports...
Valid reports: 65
Grade Counts
------------
Grade        Count  Percent
Borked       18     27.69 %
Bronze       2       3.08 %
Silver       8      12.31 %
Gold         17     26.15 %
Platinum     20     30.77 %
Comparisons to ProtonDB
-----------------------
Performance  Count  Percent 
Worse        37     56.92 %
Expected     21     32.31 %
Better       7      10.77 %
```
"Grade Counts" just counts the number of discussion posts with labels like `bronze`, `silver`, `gold`, etc. "Comparisons to ProtonDB" compares the snap's grade (`bronze`, `silver`, etc.) with the ProtonDB grade (`pdb-bronze`, `pdb-silver`, etc.) and determines if the snap grade is worse, expected, or …

Add summary flag to steam.report

---

snap/snapcraft.yaml

Turns out steam provides its own fontconfig files, if we mount it over the host fontconfig directory it just works!
Fixes #209

fix fonts by mounting steam's fontconfig

---

snap/snapcraft.yaml

Reverts update to 0.6.9-1 (from 0.6.8).
Version 0.6.9+ seems to not work well, reverting 0.6.8 seems to allow it to work as well as expected.

Revert "Update MangoHUD to 0.6.9-1"

---

src/vulkaninfo
tests/vulkan

`src/vulkaninfo` was recursively calling itself, causing it to error (and no output was generated), so its logic has been moved to `tests/vulkan` instead.
Fixes #241

Move test logic to tests/vulkan

---

snap/snapcraft.yaml

snap: connect to the network-bind interface, necessary on systems where desktop-legacy isn't supported like Ubuntu Core Desktop.

snap: connect to the network-bind interface

---

.github/ISSUE_TEMPLATE/bug_report.yml
snap/snapcraft.yaml
src/steamreport

The report dialog looks like this:
If you do not have the required plugs connected, you'll get this instead:
The CLI version can still be run by passing the new `--cli` flag, i.e. `snap run steam.report --cli`. All other flags still work with the GDK version too, like `--force` and `--verbose`.

Add GDK dialog for steamreport

---

snap/snapcraft.yaml

Reduces the amount of files to be staged for the GDK dialogs.
Currently reduces the size of the Snap from 216 MB pre-reduction to 198 MB post-reduction (still up from the 191 MB Steam in stable that does not have dialogs).

Reduce staged files for GDK dialogs

---

snap/snapcraft.yaml
src/desktop-launch

Steam tries to create the com.steampowered.PressureVessel.LaunchAlongsideSteam DBus entry, but it returns an error.
This patch fixes it.

Fix dbus error

---

snap/snapcraft.yaml
src/desktop-launch

Fixes #7
This fix requires you to restart Steam any time you install a new game to get icons for them. I couldn't get the actual game images to load as icons unless I symlinked the icons individually, instead of symlinking the directory.
This also requires you to run the following:
```
snap connect steam:dot-local-share-applications
snap connect steam:dot-local-share-icons
```

Fix desktop files not being created

---

snap/snapcraft.yaml

Binding or symlinking the `libdrm` directory just leads to an empty directory. The only file we need (and the only one that exists) in that directory is `amdgpu.ids`, so this PR just binds the file directly.
Fixes https://github.com/canonical/steam-snap/issues/176

Fix amdgpu.ids bind

---

.github/workflows/jira-sync.yml

Adds the [Jira sync action](https://github.com/canonical/sync-issues-github-jira). I've added `JIRA_WEBHOOK_URL` to our repo secrets.

ci: Add Jira sync action

---

src/nvidia32

I discovered an issue where if the NVIDIA driver version isn't determined, then the dialog will error out. This fix will replace the version with `"<your driver version>"` in cases where the version isn't determined. This also makes the version finding a bit more flexible, so that happens less often.

fix: nvidia32 cases where driver version isn't found

---

.github/workflows/autoclose.yml

Quick draft on how the action could look like.
Found this suggestion about marking them as stale if open without any activity for 30 days and closing in another 30 days. This way we could "warn" both the opener and us to reply in case something is stuck and they/we have new info to discuss.
Also, Tim talked about the possibility of not affecting existing issues. Is that something I should include in this draft?

ci: add stale issue handler action

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_reqest.yml

Since we restructured the bug and enhancement labels to be `type/bug` and `type/enhancement` respectively, the issue template auto labeling became broken, so this PR fixes that.
In addition, the bug issue template has been slimmed down a little bit to reduce friction and provide clearer direction to openers.
You can view what these templates look like by opening an issue in my repository: https://github.com/ashuntu/steam-snap/issues/new/choose.
UDENG-1869

Fix issue templates and provide clearer directions

---

snap/snapcraft.yaml

Removes the bind for `libdrm`/`amdgpu.ids` entirely. It seems like that file is automatically created and has the same contents as `$SNAP/graphics/usr/share/libdrm` anyway. The bind was previously tested, but it seems to just lead to an empty file now.
When testing, please make sure that `/usr/share/libdrm/amdgpu.ids` is populated and has the same content as `$SNAP/graphics/usr/share/libdrm/amdgpu.ids` from within the Steam snap shell. You should also *not* see errors related to missing `amdgpu.ids` when running Steam and games.
Related, and *possibly* a fix for: https://github.com/canonical/steam-snap/issues/348

Remove libdrm bind

---

snap/snapcraft.yaml

Very small PR that just removes 2 duplicate paths from staging.
`usr/**/libfontconfig*` was a direct duplicate. `usr/share/*/libgtk-3*` was a duplicate since `usr/**/libgtk-3*` already overlaps that path.

fix: Remove duplicate staged paths

---

src/desktop-launch

Fixes #369 (?) This prevents any inadvisable directories from entering the Snap environment via `XDG_CONFIG_DIRS`, `XDG_DATA_DIRS` and (for safety) `$XDG_SPECIAL_DIRS`.
In the future we may *also* want to give the snap environment access to `/var/lib/snapd/desktop` or other paths (such as `~$USER/.config/kdedefaults` or `/etc/xdg`) via a `snapd` change, but this should at least prevent SRL from *trying* to mount paths it simply cannot access. This also gives the snap in general some resiliency against users with various *other* unexpected directories stored in the `XDG_*` variables (such as the ones `flatpak` adds).
Cons: This could, in theory, strip directories that Steam actually expects to be there in the future, without any App Armor denials to inform us. To mitigate (but not remove) …

fix: strip unreachable XDG dirs

---

snap/snapcraft.yaml

Updates the required snapd version for Steam to 2.61.1 (latest) from 2.55.4. This may need to change if the latest snapd version is different when the pressure vessel changes land in snapd, so this is a draft for now.
---
UDENG-2293

fix: Update snapd assumes to 2.61.1

---

.github/workflows/build-snap.yml

currently, if the build test fails in ci, there is no way to retrigger the test unless commiting to the source branch
this adds the workflow dispatch parameter to allow the job to re-run

ci: add workflow dispatch build action trigger

---

src/desktop-launch

@ashuntu this is basically https://bugs.launchpad.net/snappy/+bug/1588192 but applied to the 32-bit paths. This fixes the issues seen in the snapd revision to give Steam more permissions and more robustly solve driver issues that Zyga gave us.

add 32-bit GL/driver paths in var/lib/snapd

---

snap/snapcraft.yaml

In updated core versions of Steam or gaming-graphics, an incorrect `LD_LIBRARY_PATH` is causing glibc not to be found. This fixes the issue.

fix: Correct LD_LIBRARY_PATH graphics directory

---

snap/snapcraft.yaml

Updates GameMode to use the original repository instead of my fork since [my fix](https://github.com/FeralInteractive/gamemode/pull/385) has been published in GameMode since [release 1.8](https://github.com/FeralInteractive/gamemode/releases/tag/1.8).

feat: Update GameMode to upstream 1.8.2

---

snap/snapcraft.yaml

Some games require that GameMode be a 32-bit library. This PR adds a build of the 32-bit versions of the GameMode libraries and binary.
You can test it by adding these launch options to a game: `gamemoderun %command%`

feat: Add 32-bit GameMode libraries

---

snap/snapcraft.yaml

There was no way previously for MangoHUD to work if it required the 32-bit versions if its libraries due to our replacing of the dynamic linker's `$LIB`. This PR fixes that and corrects the path to the libraries located in `$SNAP`.

fix: Use correct MangoHUD path on 32-bit games

---

snap/snapcraft.yaml

Use the correct changelog file name for parsechangelog to get the version. The debian package which provides that changed.

fix: Use the correct changelog file name for parsechangelog
